package lib

import (
	"fmt"
	"testing"
)

func TestDESEncrypt(t *testing.T) {

	list := []map[string]string{{
		"target": "ku1kMuU0fMY=",
		"source": "123456",
	}, {
		"target": "/z2JReJjups=",
		"source": "222222",
	}}

	for _, v := range list {
		if DESEncrypt(v["source"]) != v["target"] {
			fmt.Printf("item=%v\n", v)
		}
		if DESDecrypt(v["target"]) != v["source"] {
			fmt.Printf("item=%v\n", v)
		}
	}
}

var str = "qRVJvvZOAp4jePlEJRZatW1IzYdgZ9vHvGeuN/rXgLObL4PVDdk1owxFeoNSJbLE"

func TestDESDecrypt(t *testing.T) {
	t.Log(DESEncrypt("999999"))
	return
	//fmt.Println(DESDecrypt("qRVJvvZOAp7QR3YfqCZs02V7Dy+wEEMfU/001VAqdBgneFGahqGcuwxFeoNSJbLE"))
	//	fmt.Println(DESEncrypt(`{
	//        "version":1,
	//        "zipMd5":"B7B9400FDBF9C11B0BB0DC9F93F3B1ZC",
	//        "zipUrl":"https://cdn.hengyangtai.xyz/Face2.zip",
	//"faces":[{"id":201,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":2,"animEndPos":2,"pinyin":"ok","resultCount":0,"animRepeatCount":5,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":300,"name":"OK","nobleId":0},{"id":202,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":2,"animEndPos":2,"pinyin":"haha","resultCount":0,"animRepeatCount":6,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":260,"name":"哈哈","nobleId":0},{"id":203,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":11,"animEndPos":11,"pinyin":"zan","resultCount":0,"animRepeatCount":1,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":2200,"name":"赞","nobleId":0},{"id":204,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":4,"animEndPos":4,"pinyin":"jiayou","resultCount":0,"animRepeatCount":2,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":800,"name":"加油","nobleId":0},{"id":205,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":2,"animEndPos":2,"pinyin":"ku","resultCount":0,"animRepeatCount":5,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":300,"name":"哭","nobleId":0},{"id":206,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":9,"animEndPos":9,"pinyin":"enen","resultCount":0,"animRepeatCount":1,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":1350,"name":"嗯嗯","nobleId":0},{"id":207,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":22,"animEndPos":22,"pinyin":"shenme","resultCount":0,"animRepeatCount":1,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":2200,"name":"什么","nobleId":0},{"id":208,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":2,"animEndPos":2,"pinyin":"xiexie","resultCount":0,"animRepeatCount":5,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":300,"name":"谢谢","nobleId":0},{"id":209,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":4,"animEndPos":4,"pinyin":"chunjie","resultCount":0,"animRepeatCount":4,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":400,"name":"纯洁","nobleId":0},{"id":210,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":8,"animEndPos":8,"pinyin":"keai","resultCount":0,"animRepeatCount":1,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":1200,"name":"可爱","nobleId":0},{"id":211,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":12,"animEndPos":12,"pinyin":"hehe","resultCount":0,"animRepeatCount":1,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":1800,"name":"呵呵","nobleId":0},{"id":212,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":2,"animEndPos":2,"pinyin":"baojinwo","resultCount":0,"animRepeatCount":4,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":400,"name":"抱紧我","nobleId":0},{"id":213,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":8,"animEndPos":8,"pinyin":"chigua","resultCount":0,"animRepeatCount":1,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":1600,"name":"吃瓜","nobleId":0},{"id":214,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":2,"animEndPos":2,"pinyin":"ganga","resultCount":0,"animRepeatCount":4,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":400,"name":"尴尬","nobleId":0},{"id":215,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":10,"animEndPos":10,"pinyin":"shengqi","resultCount":0,"animRepeatCount":2,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":1000,"name":"生气","nobleId":0},{"id":216,"resultEndPos":0,"iconPos":1,"animStartPos":1,"isNobleFace":false,"canResultRepeat":0,"imageCount":10,"animEndPos":10,"pinyin":"wanan","resultCount":0,"animRepeatCount":1,"resultDuration":0,"displayType":0,"resultStartPos":0,"animDuration":1500,"name":"晚安","nobleId":0},{"id":217,"resultEndPos":16,"iconPos":0,"animStartPos":1,"isNobleFace":false,"canResultRepeat":1,"imageCount":49,"animEndPos":48,"pinyin":"baodeng","resultCount":1,"animRepeatCount":1,"resultDuration":0,"displayType":1,"resultStartPos":16,"animDuration":3000,"name":"爆灯","nobleId":0}]
	//   }`))
	t.Log(DESEncrypt(`{
        "version":1,
        "zipMd5":"9BBADD1D9D33F04E6C9D461FBCE9F86D",
        "zipUrl":"https://cdn.hengyangtai.xyz/Face2.zip",
"faces":[
    {
        "id": 217,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "hi",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "Hi",
        "nobleId": 0
    },
    {
        "id": 208,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "xiexie",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "谢谢",
        "nobleId": 0
    },
    {
        "id": 214,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "bixin",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "比心",
        "nobleId": 0
    },
    {
        "id": 207,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "jiayou",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "加油",
        "nobleId": 0
    },
    {
        "id": 213,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "bushe",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "不舍",
        "nobleId": 0
    },
    {
        "id": 203,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "zan",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "赞",
        "nobleId": 0
    },
    {
        "id": 210,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "haha",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "哈哈",
        "nobleId": 0
    },
    {
        "id": 209,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "haode",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "好的",
        "nobleId": 0
    },
    {
        "id": 205,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "motou",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "摸头",
        "nobleId": 0
    },
    {
        "id": 202,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "en",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "嗯",
        "nobleId": 0
    },
    {
        "id": 201,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "wa",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "哇",
        "nobleId": 0
    },
    {
        "id": 204,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "nanguo",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "难过",
        "nobleId": 0
    },
    {
        "id": 212,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "buyao",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "不要",
        "nobleId": 0
    },
    {
        "id": 206,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "kaixin",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "开心",
        "nobleId": 0
    },
    {
        "id": 215,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "baobao",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "抱抱",
        "nobleId": 0
    },
    {
        "id": 216,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "wanan",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "晚安",
        "nobleId": 0
    },
    {
        "id": 211,
        "resultEndPos": 0,
        "iconPos": 1,
        "animStartPos": 1,
        "isNobleFace": false,
        "canResultRepeat": 0,
        "imageCount": 8,
        "animEndPos": 8,
        "pinyin": "qinqin",
        "resultCount": 0,
        "animRepeatCount": 3,
        "resultDuration": 0,
        "displayType": 0,
        "resultStartPos": 0,
        "animDuration": 1000,
        "name": "亲亲",
        "nobleId": 0
    }
]}`))
	//t.Log(DESDecrypt("L51QfHZUnhE5fLNe75oI7l8CAsgvJcRbn/q4YdJ7OOwvahc4kILvbfjx0yUksusQqMafvJwC3MH8qnTq9BpYjOzi3Hd04FfFvPEvUOn4Ob406l18920pOnqno4BOsZWdae86iLrRX/o6XHu/s0hDdqbuBBp3Oww7auMbI6o3cwrcJlXkWLu0MPoA9mtq0iMbL8OZMVjJEu9Bm207dU5Zce+Dgd2cLYv6wveWiQnIARssdYZeF38rRBEIErU1OWV/Hd9dFWL+mpWAZ6N35Gayc3YudWCaGW/QgMstqxE3C5LubHmbwZFC/ME7KFnlZAB4"))
}
